apiVersion: v1
kind: Service
metadata:
  name: hipswriter
  namespace: default
  labels:
    app: hipswriter
spec:
  selector:
    app: hipswriter
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
