apiVersion: v1
kind: Service
metadata:
  name: hipsreader
  namespace: default
  labels:
    app: hipsreader
spec:
  selector:
    app: hipsreader
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
